### ISSUE TITLE
[clarification] about topic

### ISSUE THREAD

**Issue by djleonskennedy** [sporto/elm-tutorial#97]
in this topic I can't understand the following:

these functions:

```
updatePlayer : Player -> List Player -> List Player
updatePlayer updatedPlayer =
    let
        select existingPlayer =
            if existingPlayer.id == updatedPlayer.id then
                updatedPlayer
            else
                existingPlayer
    in
        List.map select
```

and

```
changeLevelCommands : PlayerId -> Int -> List Player -> List (Cmd Msg)
changeLevelCommands playerId howMuch =
    let
        cmdForPlayer existingPlayer =
            if existingPlayer.id == playerId then
                save { existingPlayer | level = existingPlayer.level + howMuch }
            else
                Cmd.none
    in
        List.map cmdForPlayer
```

we've got annotations for them

```
updatePlayer : Player -> List Player -> List Player
changeLevelCommands : PlayerId -> Int -> List Player -> List (Cmd Msg)
```

but they receives 

```
updatePlayer updatedPlayer = ...
changeLevelCommands playerId howMuch = ...
```

Where `List Player` comes from?

**Comment by sporto** [comment]
Hi, great question. I wrote this to add to the tutorial. Do you think this clarifies this?

# Point free style

Point free is a style of writing a function where you omit one or more arguments in the body. To understand this let's see an example.

Here we have a function that adds 10 to a number:

``` elm
add10 : Int -> Int
add10 x =
    10 + x
```

We can rewrite this using the `+` using a prefix notation:

``` elm
add10 : Int -> Int
add10 x =
    (+) 10 x
```

The argument `x` in this case is not strictly necessary, we could rewrite this as:

``` elm
add10 : Int -> Int
add10 =
    (+) 10
```

Note how `x` is missing as both an input argument to `add10` and argument to `+`. `add10` is still a function that requires and integer to calculate a result. Omitting arguments likes this is called **point free style**.

## Some more examples

``` elm
select : Int -> List Int -> List Int 
select num list =
    List.filter (\x -> x < num) list

select 4 [1, 2, 3, 4, 5] == [1, 2, 3]
```

is the same as:

``` elm
select : Int -> List Int -> List Int 
select num =
    List.filter (\x -> x < num)

select 4 [1, 2, 3, 4, 5] == [1, 2, 3]
```

---

``` elm
process : List Int -> List Int 
process list =
    reverse list |> drop 3
```

is the same as:

``` elm
process : List Int -> List Int 
process =
    reverse >> drop 3
```

**Comment by dbackeus** [comment]
I faced the same conundrum going through the tutorial. Read your examples and also googled some articles mentioning it.

Since I still don't feel that it's adding anything to code clarity (even though I understand _how_ it works) I'm assuming it's the kind of thing that only starts feeling intuitional / comfortable after spending more time with functional programming.

Your suggested text is a great starting point and it's probably a good idea to introduce the reader to the concept since it's no doubt something that they will have to face sooner or later.

Maybe something like "If this still looks weird to you, don't worry, you can write in the more explicit style if you prefer but be aware that idiomatic functional programming often adheres to this approach." could be added at the end (there is probably a simpler way of phrasing that sentence).

I was hoping that one of the articles I came across could be used as a "read more" link but to be honest they didn't really add much for me as a beginner since they seemed to be targeting people who were already familiar with Haskell and taking for granted that the free point style would be seen as superior from the get go.

**Comment by sporto** [comment]
Thanks for the response, I am leaning towards removing this style from the tutorial. It seems to just add unnecessary confusion (even if more idiomatic).

**Comment by dbackeus** [comment]
Yeah it might be more straight forward to leave it out of the tutorial itself. Another approach would be to add it to the "Improvement" section or to its own "Tips and Trix" section.

Thanks for the great tutorial in any case 👍

**Comment by djleonskennedy** [comment]
@sporto Thank you, now it's clear))) in general your tutorial is awesome!

NOTE: would be cool if tutorial also describe: (router query parameters and permissions :)

**Comment by djleonskennedy** [comment]
also here nice talk about `point-free`

https://www.youtube.com/watch?v=seVSlKazsNk
